// webmail/referenceTemplates/astro/headings/card-headings/05-with-description.tsx
/** @jsxImportSource preact */
export default function Example() {
  return (
    <div className="border-b border-gray-200 px-4 py-5 sm:px-6 dark:border-white/10">
      <h3 className="text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
      <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
        Lorem ipsum dolor sit amet consectetur adipisicing elit quam corrupti consectetur.
      </p>
    </div>
  )
}

// webmail/referenceTemplates/tailwindcss.com/vue/headings/card-headings/05-with-description.vue
<template>
  <div class="border-b border-gray-200 px-4 py-5 sm:px-6 dark:border-white/10">
    <h3 class="text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
    <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
      Lorem ipsum dolor sit amet consectetur adipisicing elit quam corrupti consectetur.
    </p>
  </div>
</template>
