// webmail/referenceTemplates/tailwindcss.com/vue/layout/cards/06-card-with-gray-footer.vue
<template>
  <div
    class="overflow-hidden rounded-lg bg-white shadow-sm dark:divide-white/10 dark:bg-gray-800/50 dark:shadow-none dark:outline dark:-outline-offset-1 dark:outline-white/10"
  >
    <div class="px-4 py-5 sm:p-6">
      <!-- Content goes here -->
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6 dark:bg-gray-800/50">
      <!-- Content goes here -->
      <!-- We use less vertical padding on card footers at all sizes than on headers or body sections -->
    </div>
  </div>
</template>

// webmail/referenceTemplates/tailwindcss.com/react/layout/cards/06-card-with-gray-footer.jsx
export default function Example() {
  return (
    <div className="overflow-hidden rounded-lg bg-white shadow-sm dark:divide-white/10 dark:bg-gray-800/50 dark:shadow-none dark:outline dark:-outline-offset-1 dark:outline-white/10">
      <div className="px-4 py-5 sm:p-6">{/* Content goes here */}</div>
      <div className="bg-gray-50 px-4 py-4 sm:px-6 dark:bg-gray-800/50">
        {/* Content goes here */}
        {/* We use less vertical padding on card footers at all sizes than on headers or body sections */}
      </div>
    </div>
  );
}
