// webmail/referenceTemplates/tailwindcss.com/vue/layout/dividers/04-with-title.vue
<template>
  <div class="flex items-center">
    <div class="w-full border-t border-gray-300 dark:border-white/15" aria-hidden="true"></div>
    <div class="relative flex justify-center">
      <span
        class="bg-white px-3 text-base font-semibold text-gray-900 dark:bg-gray-900 dark:text-white"
        >Projects</span
      >
    </div>
    <div class="w-full border-t border-gray-300 dark:border-white/15" aria-hidden="true"></div>
  </div>
</template>

// webmail/referenceTemplates/tailwindcss.com/react/layout/dividers/04-with-title.jsx
export default function Example() {
  return (
    <div className="flex items-center">
      <div aria-hidden="true" className="w-full border-t border-gray-300 dark:border-white/15" />
      <div className="relative flex justify-center">
        <span className="bg-white px-3 text-base font-semibold text-gray-900 dark:bg-gray-900 dark:text-white">
          Projects
        </span>
      </div>
      <div aria-hidden="true" className="w-full border-t border-gray-300 dark:border-white/15" />
    </div>
  );
}
