// webmail/referenceTemplates/tailwindcss.com/vue/layout/media-objects/07-wide-responsive.vue
<template>
  <div class="sm:flex">
    <div class="mb-4 shrink-0 sm:mr-4 sm:mb-0">
      <svg
        class="h-32 w-full border border-gray-300 bg-white text-gray-300 sm:w-32 dark:border-white/15 dark:bg-gray-900 dark:text-white/15"
        preserveAspectRatio="none"
        stroke="currentColor"
        fill="none"
        viewBox="0 0 200 200"
        aria-hidden="true"
      >
        <path vector-effect="non-scaling-stroke" stroke-width="1" d="M0 0l200 200M0 200L200 0" />
      </svg>
    </div>
    <div>
      <h4 class="text-lg font-bold text-gray-900 dark:text-white">Lorem ipsum</h4>
      <p class="mt-1 text-gray-500 dark:text-gray-400">
        Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis
        voluptatem. Minus quidem ipsam quia iusto.
      </p>
    </div>
  </div>
</template>

// webmail/referenceTemplates/astro/layout/media-objects/07-wide-responsive.tsx
/** @jsxImportSource preact */
export default function Example() {
  return (
    <div className="sm:flex">
      <div className="mb-4 shrink-0 sm:mr-4 sm:mb-0">
        <svg
          fill="none"
          stroke="currentColor"
          viewBox="0 0 200 200"
          preserveAspectRatio="none"
          aria-hidden="true"
          className="h-32 w-full border border-gray-300 bg-white text-gray-300 sm:w-32 dark:border-white/15 dark:bg-gray-900 dark:text-white/15"
        >
          <path d="M0 0l200 200M0 200L200 0" strokeWidth={1} vectorEffect="non-scaling-stroke" />
        </svg>
      </div>
      <div>
        <h4 className="text-lg font-bold text-gray-900 dark:text-white">Lorem ipsum</h4>
        <p className="mt-1 text-gray-500 dark:text-gray-400">
          Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus
          quidem ipsam quia iusto.
        </p>
      </div>
    </div>
  )
}
