// webmail/referenceTemplates/tailwindcss.com/react/forms/textareas/01-simple.jsx
export default function Example() {
  return (
    <div>
      <label
        htmlFor="comment"
        className="block text-sm/6 font-medium text-gray-900 dark:text-white"
      >
        Add your comment
      </label>
      <div className="mt-2">
        <textarea
          id="comment"
          name="comment"
          rows={4}
          className="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
          defaultValue={""}
        />
      </div>
    </div>
  );
}

// webmail/referenceTemplates/tailwindcss.com/vue/forms/textareas/01-simple.vue
<template>
  <div>
    <label for="comment" class="block text-sm/6 font-medium text-gray-900 dark:text-white"
      >Add your comment</label
    >
    <div class="mt-2">
      <textarea
        rows="4"
        name="comment"
        id="comment"
        class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
      ></textarea>
    </div>
  </div>
</template>
