// webmail/referenceTemplates/tailwindcss.com/vue/forms/input-groups/06-input-with-corner-hint.vue
<template>
  <div>
    <div class="flex justify-between">
      <label for="email" class="block text-sm/6 font-medium text-gray-900 dark:text-white"
        >Email</label
      >
      <span class="text-sm/6 text-gray-500 dark:text-gray-400" id="email-optional">Optional</span>
    </div>
    <div class="mt-2">
      <input
        type="email"
        name="email"
        id="email"
        class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
        placeholder="you@example.com"
        aria-describedby="email-optional"
      />
    </div>
  </div>
</template>

// webmail/referenceTemplates/astro/forms/input-groups/06-input-with-corner-hint.tsx
/** @jsxImportSource preact */
export default function Example() {
  return (
    <div>
      <div className="flex justify-between">
        <label htmlFor="email" className="block text-sm/6 font-medium text-gray-900 dark:text-white">
          Email
        </label>
        <span id="email-optional" className="text-sm/6 text-gray-500 dark:text-gray-400">
          Optional
        </span>
      </div>
      <div className="mt-2">
        <input
          id="email"
          name="email"
          type="email"
          placeholder="you@example.com"
          aria-describedby="email-optional"
          className="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
        />
      </div>
    </div>
  )
}
