// webmail/referenceTemplates/tailwindcss.com/vue/headings/section-headings/04-with-action.vue
<template>
  <div
    class="border-b border-gray-200 pb-5 sm:flex sm:items-center sm:justify-between dark:border-white/10"
  >
    <h3 class="text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
    <div class="mt-3 sm:mt-0 sm:ml-4">
      <button
        type="button"
        class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 dark:bg-indigo-500 dark:shadow-none dark:hover:bg-indigo-400 dark:focus-visible:outline-indigo-500"
      >
        Create new job
      </button>
    </div>
  </div>
</template>

// webmail/referenceTemplates/astro/headings/section-headings/04-with-action.tsx
/** @jsxImportSource preact */
export default function Example() {
  return (
    <div className="border-b border-gray-200 pb-5 sm:flex sm:items-center sm:justify-between dark:border-white/10">
      <h3 className="text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
      <div className="mt-3 sm:mt-0 sm:ml-4">
        <button
          type="button"
          className="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 dark:bg-indigo-500 dark:shadow-none dark:hover:bg-indigo-400 dark:focus-visible:outline-indigo-500"
        >
          Create new job
        </button>
      </div>
    </div>
  )
}
