// webmail/referenceTemplates/tailwindcss.com/react/feedback/alerts/02-with-list.jsx
import { XCircleIcon } from "@heroicons/react/20/solid";

export default function Example() {
  return (
    <div className="rounded-md bg-red-50 p-4 dark:bg-red-500/15 dark:outline dark:outline-red-500/25">
      <div className="flex">
        <div className="shrink-0">
          <XCircleIcon aria-hidden="true" className="size-5 text-red-400" />
        </div>
        <div className="ml-3">
          <h3 className="text-sm font-medium text-red-800 dark:text-red-200">
            There were 2 errors with your submission
          </h3>
          <div className="mt-2 text-sm text-red-700 dark:text-red-200/80">
            <ul role="list" className="list-disc space-y-1 pl-5">
              <li>Your password must be at least 8 characters</li>
              <li>Your password must include at least one pro wrestling finishing move</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

// webmail/referenceTemplates/tailwindcss.com/vue/feedback/alerts/02-with-list.vue
<template>
  <div class="rounded-md bg-red-50 p-4 dark:bg-red-500/15 dark:outline dark:outline-red-500/25">
    <div class="flex">
      <div class="shrink-0">
        <XCircleIcon class="size-5 text-red-400" aria-hidden="true" />
      </div>
      <div class="ml-3">
        <h3 class="text-sm font-medium text-red-800 dark:text-red-200">
          There were 2 errors with your submission
        </h3>
        <div class="mt-2 text-sm text-red-700 dark:text-red-200/80">
          <ul role="list" class="list-disc space-y-1 pl-5">
            <li>Your password must be at least 8 characters</li>
            <li>Your password must include at least one pro wrestling finishing move</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { XCircleIcon } from "@heroicons/vue/20/solid";
</script>
