// webmail/referenceTemplates/tailwindcss.com/react/layout/dividers/01-with-label.jsx
export default function Example() {
  return (
    <div className="flex items-center">
      <div aria-hidden="true" className="w-full border-t border-gray-300 dark:border-white/15" />
      <div className="relative flex justify-center">
        <span className="bg-white px-2 text-sm text-gray-500 dark:bg-gray-900 dark:text-gray-400">
          Continue
        </span>
      </div>
      <div aria-hidden="true" className="w-full border-t border-gray-300 dark:border-white/15" />
    </div>
  );
}

// webmail/referenceTemplates/tailwindcss.com/vue/layout/dividers/01-with-label.vue
<template>
  <div class="flex items-center">
    <div class="w-full border-t border-gray-300 dark:border-white/15" aria-hidden="true"></div>
    <div class="relative flex justify-center">
      <span class="bg-white px-2 text-sm text-gray-500 dark:bg-gray-900 dark:text-gray-400"
        >Continue</span
      >
    </div>
    <div class="w-full border-t border-gray-300 dark:border-white/15" aria-hidden="true"></div>
  </div>
</template>
