// webmail/referenceTemplates/tailwindcss.com/react/elements/avatars/01-circular-avatars.jsx
export default function Example() {
  return (
    <>
      <img
        alt=""
        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
        className="inline-block size-6 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
      />
      <img
        alt=""
        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
        className="inline-block size-8 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
      />
      <img
        alt=""
        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
        className="inline-block size-10 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
      />
      <img
        alt=""
        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
        className="inline-block size-12 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
      />
      <img
        alt=""
        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
        className="inline-block size-14 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
      />
    </>
  );
}

// webmail/referenceTemplates/tailwindcss.com/vue/elements/avatars/01-circular-avatars.vue
<template>
  <img
    class="inline-block size-6 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
    src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
    alt=""
  />
  <img
    class="inline-block size-8 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
    src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
    alt=""
  />
  <img
    class="inline-block size-10 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
    src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
    alt=""
  />
  <img
    class="inline-block size-12 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
    src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
    alt=""
  />
  <img
    class="inline-block size-14 rounded-full outline -outline-offset-1 outline-black/5 dark:outline-white/10"
    src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
    alt=""
  />
</template>
