// webmail/referenceTemplates/astro/forms/input-groups/19-input-with-pill-shape.tsx
/** @jsxImportSource preact */
export default function Example() {
  return (
    <div>
      <label htmlFor="name" className="ml-px block pl-4 text-sm/6 font-medium text-gray-900 dark:text-white">
        Name
      </label>
      <div className="mt-2">
        <input
          id="name"
          name="name"
          type="text"
          placeholder="Jane Smith"
          className="block w-full rounded-full bg-white px-4 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
        />
      </div>
    </div>
  )
}

// webmail/referenceTemplates/tailwindcss.com/vue/forms/input-groups/19-input-with-pill-shape.vue
<template>
  <div>
    <label for="name" class="ml-px block pl-4 text-sm/6 font-medium text-gray-900 dark:text-white"
      >Name</label
    >
    <div class="mt-2">
      <input
        type="text"
        name="name"
        id="name"
        class="block w-full rounded-full bg-white px-4 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
        placeholder="Jane Smith"
      />
    </div>
  </div>
</template>
